name: mgrs_dart
description: Utility for converting between WGS84 lat/lng and MGRS coordinates (Dart version of proj4js/mgrs).
version: 3.0.0
homepage: https://github.com/fegyi001/mgrs_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  unicode: ^1.1.8

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.25.15
